Importando bibliotecas

In [1]:
import pandas as pd
import sys

lendo arquivo

In [2]:
df = pd.read_excel("semanal-estados-desde-2013.xlsx",header=17, engine="openpyxl")

Vendo estrutura basica do dataframe

In [5]:
print("DataFrame criado com ", df.shape[0], "linhas e ", df.shape[1] ," colunas")

DataFrame criado com  112079 linhas e  18  colunas

tipo das colunas

In [10]:
df.dtypes

DATA INICIAL                     datetime64[ns]
DATA FINAL                       datetime64[ns]
REGIÃO                                   object
ESTADO                                   object
PRODUTO                                  object
NÚMERO DE POSTOS PESQUISADOS              int64
UNIDADE DE MEDIDA                        object
PREÇO MÉDIO REVENDA                     float64
DESVIO PADRÃO REVENDA                   float64
PREÇO MÍNIMO REVENDA                    float64
PREÇO MÁXIMO REVENDA                    float64
MARGEM MÉDIA REVENDA                     object
COEF DE VARIAÇÃO REVENDA                float64
PREÇO MÉDIO DISTRIBUIÇÃO                 object
DESVIO PADRÃO DISTRIBUIÇÃO               object
PREÇO MÍNIMO DISTRIBUIÇÃO                object
PREÇO MÁXIMO DISTRIBUIÇÃO                object
COEF DE VARIAÇÃO DISTRIBUIÇÃO            object
dtype: object

Nulos reais

In [15]:
nulos = df.isnull().sum()

nulos_pct = (nulos / len(df) * 100).round(2)

resumo_nulos = pd.DataFrame({"nulos": nulos, "pct_%": nulos_pct})
print(resumo_nulos[resumo_nulos["nulos"] > 0]
      if resumo_nulos["nulos"].sum() > 0
      else "Nenhum nulo real encontrado.")

Nenhum nulo real encontrado.

Nulos disfarçados (traços, vazios e zeros suspeitos)

In [40]:
SUSPEITOS = ["-", "--", "N/A", "n/a", "NA", "null", "NULL", " ", ""]

for col in df.select_dtypes(include="object").columns:
    contagem = df[col].isin(SUSPEITOS).sum()
    if contagem > 0:
        exemplos = df[col][df[col].isin(SUSPEITOS)].unique()[:3].tolist()
        print(f"  {col:<45} {contagem:>7,} ocorrências  ex: {exemplos}")

Dominio das categorias

In [44]:
for col in df.select_dtypes(include="object").columns:
    unicos = df[col].dropna().unique()
    tamanho = len(unicos)

    print(f"\nColuna: {col} ({tamanho} valores únicos)")


    if tamanho <= 30:
        print(unicos)
    else:
        print("Primeiros",unicos[:5])
        print("Ultimos: ", unicos[-5:])

Coluna: REGIÃO (5 valores únicos)
['NORTE' 'NORDESTE' 'CENTRO OESTE' 'SUDESTE' 'SUL']

Coluna: ESTADO (27 valores únicos)
['ACRE' 'ALAGOAS' 'AMAPA' 'AMAZONAS' 'BAHIA' 'CEARA' 'DISTRITO FEDERAL'
 'ESPIRITO SANTO' 'GOIAS' 'MARANHAO' 'MATO GROSSO' 'MATO GROSSO DO SUL'
 'MINAS GERAIS' 'PARA' 'PARAIBA' 'PARANA' 'PERNAMBUCO' 'PIAUI'
 'RIO DE JANEIRO' 'RIO GRANDE DO NORTE' 'RIO GRANDE DO SUL' 'RONDONIA'
 'RORAIMA' 'SANTA CATARINA' 'SAO PAULO' 'SERGIPE' 'TOCANTINS']

Coluna: PRODUTO (7 valores únicos)
['ETANOL HIDRATADO' 'GASOLINA COMUM' 'GLP' 'GNV' 'OLEO DIESEL'
 'OLEO DIESEL S10' 'GASOLINA ADITIVADA']

Coluna: UNIDADE DE MEDIDA (5 valores únicos)
['R$/l' 'R$/13Kg' 'R$/m3' 'R$/13kg' 'R$/m³']

Coluna: MARGEM MÉDIA REVENDA (8438 valores únicos)
Primeiros [0.428 0.27 0.189 0.286 0.172]
Ultimos:  [15.476 19.147 17.486 14.103 22.671]

Coluna: PREÇO MÉDIO DISTRIBUIÇÃO (10819 valores únicos)
Primeiros [2.125 2.038 2.126 1.881 2.029]
Ultimos:  [53.932 47.196 53.84 54.929 51.166]

Coluna: DESVIO PADRÃO DISTRIBUIÇÃO (5179 valores únicos)
Primeiros [0.17 0.061 0.045 0.118 0.042]
Ultimos:  [0.761 4.841 2.666 4.449 5.442]

Coluna: PREÇO MÍNIMO DISTRIBUIÇÃO (15061 valores únicos)
Primeiros [1.6239 1.9056 1.9941 1.62 1.9127]
Ultimos:  [2.1399 1.9832 3.759 70.38 2.9328]

Coluna: PREÇO MÁXIMO DISTRIBUIÇÃO (16433 valores únicos)
Primeiros [2.2744 2.2231 2.2169 2.14 2.0908]
Ultimos:  [3.0603 3.093 3.6283 3.2084 3.8237]

Coluna: COEF DE VARIAÇÃO DISTRIBUIÇÃO (276 valores únicos)
Primeiros [0.08 0.03 0.021 0.063 0.009]
Ultimos:  [0.29 0.591 0.437 0.241 0.264]

Estatisticas basicas sobre o dataset

In [21]:
df.describe(include="number")

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,COEF DE VARIAÇÃO REVENDA
count,112079.000000,112079.000000,112079.000000,112079.000000,112079.000000,112079.000000
mean,144.078926,16.596158,1.066887,14.395393,19.340254,0.046179
std,250.297070,29.758775,2.288549,25.411056,35.191242,0.025108
min,1.000000,1.503000,0.000000,1.259000,1.690000,0.000000
25%,29.000000,3.237000,0.110000,2.990000,3.599000,0.030000
50%,60.000000,4.546000,0.180000,4.220000,4.999000,0.042000
75%,156.000000,6.392500,0.324000,5.950000,7.170000,0.059000
max,2383.000000,142.630000,19.347000,132.000000,170.000000,0.591000

In [23]:
df.head(3)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2012-12-30,2013-01-05,NORTE,ACRE,ETANOL HIDRATADO,33,R$/l,2.553,0.098,2.42,3.00,0.428,0.038,2.125,0.17,1.6239,2.2744,0.08
1,2012-12-30,2013-01-05,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.308,0.066,2.19,2.44,0.27,0.029,2.038,0.061,1.9056,2.2231,0.03
2,2012-12-30,2013-01-05,NORTE,AMAPA,ETANOL HIDRATADO,7,R$/l,2.260,0.045,2.18,2.32,-,0.020,-,-,-,-,-

quantas linhas existem para cada combinação de produto + unidade de medida?

In [29]:
df.groupby(["PRODUTO", "UNIDADE DE MEDIDA"]).size().reset_index(name="contagem").sort_values("PRODUTO")

              PRODUTO UNIDADE DE MEDIDA  contagem
0    ETANOL HIDRATADO              R$/l     18415
1  GASOLINA ADITIVADA              R$/l      7831
2      GASOLINA COMUM              R$/l     18592
3                 GLP           R$/13Kg     10661
4                 GLP           R$/13kg      7902
5                 GNV             R$/m3      6615
6                 GNV             R$/m³      4946
7         OLEO DIESEL              R$/l     18539
8     OLEO DIESEL S10              R$/l     18578

In [36]:
for col in df.select_dtypes(include="object").columns:
    df[col].replace("-", None, inplace=True)

C:\Users\ygorc\AppData\Local\Temp\ipykernel_22808\3677425014.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace("-", None, inplace=True)

In [43]:
SUSPEITOS = ["-", "--", "N/A", "n/a", "NA", "null", "NULL", " ", "None"]

for col in df.select_dtypes(include="object").columns:
    contagem = df[col].isin(SUSPEITOS).sum()
    if contagem > 0:
        exemplos = df[col][df[col].isin(SUSPEITOS)].unique()[:3].tolist()
        print(f"  {col:<45} {contagem:>7,} ocorrências  ex: {exemplos}")

In [41]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2012-12-30,2013-01-05,NORTE,ACRE,ETANOL HIDRATADO,33,R$/l,2.553,0.098,2.42,3.000,0.428,0.038,2.125,0.17,1.6239,2.2744,0.08
1,2012-12-30,2013-01-05,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.308,0.066,2.19,2.440,0.27,0.029,2.038,0.061,1.9056,2.2231,0.03
2,2012-12-30,2013-01-05,NORTE,AMAPA,ETANOL HIDRATADO,7,R$/l,2.260,0.045,2.18,2.320,None,0.020,None,None,None,None,None
3,2012-12-30,2013-01-05,NORTE,AMAZONAS,ETANOL HIDRATADO,70,R$/l,2.315,0.080,2.22,2.620,0.189,0.035,2.126,0.045,1.9941,2.2169,0.021
4,2012-12-30,2013-01-05,NORDESTE,BAHIA,ETANOL HIDRATADO,414,R$/l,2.167,0.127,1.85,2.599,0.286,0.059,1.881,0.118,1.62,2.14,0.063